services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.8
    ports:
      - '8888:8080'
    environment:
      JSON_CONFIG: '{"interactiveLogin":false}'
  wonderwall:
    image: ghcr.io/nais/wonderwall:latest
    ports:
      - '3005:3005'
    command: >
      --openid.client-id=nav-epj
      --openid.client-secret=not-so-secret
      --openid.well-known-url=http://localhost:8888/default/.well-known/openid-configuration
      --ingress=http://localhost:3005
      --bind-address=0.0.0.0:3005
      --upstream-host=localhost:3000
      --redis.uri=redis://redis:6379
      --auto-login=true
      --log-level=debug
      --log-format=text
    restart: on-failure
    depends_on:
      - mock-oauth2-server
      - redis
    extra_hosts:
      - localhost:host-gateway
