include:
  - docker-compose-wonderwall.yml
services:
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.8
    ports:
      - '8888:8080'
    environment:
      JSON_CONFIG: |
        {
          "interactiveLogin": false,
          "tokenCallbacks": [
            {
              "issuerId": "helseid",
              "tokenExpiry": 3600,
              "requestMappings": [
                {
                  "requestParam": "grant_type",
                  "match": "*",
                  "claims": {
                    "client_id": "nav-epj",
                    "sub": "12345678901",
                    "pid": "12345678901",
                    "client_amr": "private_key_jwt",
                    "amr": [
                      "pwd"
                    ],
                    "scope": [
                      "openid",
                      "profile",
                      "helseid://scopes/identity/assurance_level",
                      "helseid://scopes/identity/pid",
                      "helseid://scopes/identity/security_level",
                      "helseid://scopes/hpr/hpr_number",
                      "helseid://scopes/identity/network",
                      "offline_access"
                    ],
                    "mordi": "fardin"
                  }
                }
              ]
            }
          ]
        }
