apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-epj
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  valkey:
    - instance: nav-epj
      access: readwrite
  image: {{image}}
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        name: nav-epj-db-instance
        cascadingDelete: false
        tier: db-f1-micro
        databases:
          - name: nav-epj
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"

  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 30m
      memory: 512Mi

  liveness:
    path: /internal/health/alive
    initialDelay: 30
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/health/ready
    initialDelay: 30
    periodSeconds: 5
  preStopHook:
    http:
      path: /internal/shutdown
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java

  ingresses:
    - 'https://epj.ansatt.dev.nav.no'

  login:
    provider: openid
    enforce:
      enabled: true
      excludePaths:
        - /auth/**
        - /api/**

  accessPolicy:
    outbound:
      external:
        - host: 'helseid-sts.test.nhn.no'

  envFrom:
    - secret: login-config-nav-epj

  env:
    - name: FHIR_SERVER_URL
      value: https://epj.ansatt.dev.nav.no/fhir
    - name: SMART_ISSUER_BASE_URL
      value: https://epj.ansatt.dev.nav.no/oidc
