ktor:
  application:
    modules:
      - no.nav.helse.ApplicationKt.module
  deployment:
    port: 8080
    watch:
      - classes
      - resources

database:
  url: "jdbc:postgresql://localhost:5434/nav-epj"
  user: "postgres"
  password: "postgres"

smart:
  issuerBaseUrl: "http://localhost:8080/oidc"
  fhirServerUrl: "http://localhost:8080/fhir"
  clients:
    - clientId: "syk-inn"
      redirectUris: ["http://localhost:3000"]
      launchUris: ["http://localhost:3000/fhir/launch"]
    - clientId: "NAV_SMART_on_FHIR_example"
      redirectUris: ["http://localhost:5174/"]
      launchUris: ["http://localhost:5174/launch"]

valkey:
  host: localhost
  port: 6379
  useTLS: false