ktor:
  application:
    modules:
      - no.nav.tsm.ApplicationKt.module
  deployment:
    port: 8080

auth:
  helseId:
    wellKnownUrl: ${WONDERWALL_OPENID_WELL_KNOWN_URL}
    clientId: ${WONDERWALL_OPENID_CLIENT_ID}
