ktor:
  application:
    modules:
      - no.nav.helse.ApplicationKt.module
  deployment:
    port: 8080

database:
  url: ${DB_JDBC_URL}
  user: ${DB_USERNAME}
  password: ${DB_PASSWORD}

epj:
  baseUrl: "http://localhost:8080"

auth:
  helseId:
    wellKnownUrl: ${WONDERWALL_OPENID_WELL_KNOWN_URL}
    clientId: ${WONDERWALL_OPENID_CLIENT_ID}

smart:
  issuerBaseUrl: ${SMART_ISSUER_BASE_URL}
  fhirServerUrl: ${FHIR_SERVER_URL}
  clients:
    - clientId: "syk-inn"
      redirectUris: [ "https://www.ekstern.dev.nav.no/samarbeidspartner/sykmelding", "https://www.ekstern.dev.nav.no/samarbeidspartner/sykmelding/fhir/callback" ]
      launchUris: [ "https://www.ekstern.dev.nav.no/samarbeidspartner/sykmelding/fhir/launch" ]
      tokenEndpointAuthMethod: "private_key_jwt"
      jwksUri: "https://www.ekstern.dev.nav.no/samarbeidspartner/sykmelding/fhir/jwks.json"
      scopes:
        - openid
        - fhirUser
        - launch
        - offline_access
        - patient/Patient.rs
        - patient/Encounter.rs
        - patient/DocumentReference.crs
    - clientId: "NAV_SMART_on_FHIR_validator"
      redirectUris: [ "https://nav-on-fhir.ekstern.dev.nav.no" ]
      launchUris: [ "https://nav-on-fhir.ekstern.dev.nav.no/launch" ]
      tokenEndpointAuthMethod: "private_key_jwt"
      jwksUri: "https://nav-on-fhir.ekstern.dev.nav.no/jwks.json"
      scopes:
        - openid
        - fhirUser
        - launch
        - patient/*.rs
        - user/*.rs

valkey:
  host: ${VALKEY_HOST_NAV_EPJ}
  port: ${VALKEY_PORT_NAV_EPJ}
  useTLS: true
  username: ${VALKEY_USERNAME_NAV_EPJ}
  password: ${VALKEY_PASSWORD_NAV_EPJ}

