export const copy = {
  "app.name": "nav-epj",
  "app.subtitle": "Test-EPJ",
  "app.test": "TEST",
  "app.testTooltip": "Testmiljø – kun syntetiske data",
  "header.search.label": "Søk etter pasient",
  "header.search.placeholder": "Søk pasient: navn eller fnr (Ctrl+Shift+P)",
  "header.search.placeholderNarrow": "Søk pasient",
  "header.user": (navn: string, autorisasjon: string, legekontor: string) => `${navn} · ${autorisasjon} · ${legekontor}`,
  "header.logout": "Logg av",
  "header.menu": "Meny",
  "nav.label": "Oppgaver",
  "pane.patient.title": "Pasient",
  "pane.patient.none": "Ingen pasient valgt.",
  "pane.patient.info": (dato: string, alder: number, kjonn: string) => `Født ${dato} (${alder} år) · ${kjonn}`,
  "pane.patient.openJournal": "Åpne journal",
  "pane.patient.find": "Finn pasient",
  "pane.patient.findOther": "Finn en annen pasient",
  "pane.apps.title": "SMART-apper",
  "pane.apps.mode.iframe": "▣ Vindu",
  "pane.apps.mode.tab": "↗ Ny fane",
  "pane.apps.mode.ask": "? Spør",
  "pane.apps.runningHost": "● Kjører i nav-epj",
  "pane.apps.runningTab": "↗ Kjører i egen fane – verten kan ikke lukke den",
  "pane.apps.stale": "Tilhører forrige pasient – lukk fanen",
  "pane.apps.disabledReason": "Start en konsultasjon først. Apper trenger en pågående konsultasjon.",
  "pane.apps.startTooltip": (app: string) => `Start ${app}`,
  "pane.system.title": "System",
  "pane.system.patients": "Pasienter",
  "pane.system.kontroll": "Kontrollpanel",
  "pane.system.sysinfo": "Systeminformasjon",
  "pane.system.logg": "Hendelseslogg",
  "pane.system.hjelp": "Hjelp",
  "pane.system.logoutNarrow": (navn: string) => `Logg av ${navn}`,
  "pane.soon.title": "Kommer",
  "pane.soon.kj": "Kjernejournal",
  "pane.soon.er": "e-resept",
  "pane.soon.em": "e-meldinger",
  "pane.soon.label": "Kommer",
  "badge.phase2": "Fase 2",
  "badge.example": "Eksempel",
  "badge.localOnly": "⚙ Kun lokalt",
  "tabs.label": "Åpne arbeidsflater",
  "tabs.start": "Start",
  "tabs.journal": (navn: string) => `Journal · ${navn}`,
  "tabs.app": (app: string, initialer: string) => `${app} · ${initialer}`,
  "tabs.app.aria": (app: string, navn: string, status: string) => `${app} for ${navn}, ${status}`,
  "tabs.close": (fane: string) => `Lukk ${fane}`,
  "tabs.closeTooltip": "Lukk (Ctrl+W)",
  "tabs.logg": "Hendelseslogg (Fase 2)",
  "status.label": "Statuslinje",
  "status.ready": "Klar",
  "status.hits": (n: number) => `${n} treff`,
  "status.patient": (navn: string) => `Aktiv pasient: ${navn}`,
  "status.patient.aria": (navn: string) => `Aktiv pasient: ${navn}. Åpne journal.`,
  "status.noPatient": "Ingen pasient valgt",
  "status.noPatient.aria": "Ingen aktiv pasient. Åpne pasientlisten.",
  "status.kons": (min: number) => `◐ Konsultasjon ${min} min`,
  "status.tabApps": (n: number) =>
    n === 1 ? `↗ ${n} app i egen fane` : `↗ ${n} apper i egen fane`,
  "status.staleApps": (n: number) => `⚠ ${n} app i fane tilhører forrige pasient`,
  "status.clock.sr": (tid: string) => `Klokken er ${tid}`,
  "balloon.close": "Lukk varsel",
  "context.label": "Pasientkontekst",
  "context.fnr": "Fødselsnummer",
  "context.fnrShow": "Vis",
  "context.fnrHide": "Skjul",
  "context.born": "Født",
  "context.age": "Alder",
  "context.ageValue": (n: number) => `${n} år`,
  "context.gender.m": "Mann",
  "context.gender.k": "Kvinne",
  "context.office": "Legekontor",
  "context.orgnr": "Org.nr.",
  "context.stale": "⚠ Utdatert",
  "live.fnrShown": "Fødselsnummer vises.",
  "live.fnrHidden": "Fødselsnummer skjult.",
  "live.journalOpened": (navn: string) => `Journal åpnet for ${navn}.`,
  "live.switched": (fra: string, til: string) => `Aktiv pasient byttet fra ${fra} til ${til}.`,
  "live.konsStarted": (navn: string) => `Konsultasjon startet for ${navn}.`,
  "live.konsDone": "Konsultasjonen er fullført.",
  "live.appRunning": (app: string) => `${app} kjører.`,
  "live.appTab": (app: string) => `${app} åpnet i ny fane.`,
  "live.back": (app: string) => `Tilbake i ${app}.`,
  "live.forward": (app: string) => `Frem i ${app}.`,
  "live.theme": (tema: string) => `Tema byttet til ${tema}.`,
  "s1.tagline": "Test-EPJ for SMART on FHIR",
  "s1.loading": "Henter brukeropplysninger …",
  "s1.loadingDetail": "Du er logget inn med HelseID. Venter på svar fra nav-epj.",
  "s1.welcome": (navn: string) => `Velkommen, ${navn}`,
  "s1.userLine": (autorisasjon: string, hpr: string) => `${autorisasjon} · HPR ${hpr}`,
  "s1.officeLine": (legekontor: string, orgnr: string) => `${legekontor} · org.nr. ${orgnr}`,
  "s1.continue": "Klikk på navnet ditt eller trykk Enter for å fortsette.",
  "s1.error.title": "Kunne ikke hente brukeropplysningene dine.",
  "s1.error.body": "Du er logget inn med HelseID, men nav-epj svarte ikke. Prøv igjen. Hvis feilen fortsetter, logg av og inn på nytt.",
  "s1.error.retry": "Prøv igjen",
  "s1.footer.test": "Testmiljø – kun syntetiske data",
  "s1.footer.login": "Innlogging skjer i HelseID før denne siden lastes.",
  "s2.greeting": (navn: string) => `God morgen, ${navn}`,
  "s2.find.title": "Finn pasient",
  "s2.find.body": "Søk i feltet øverst, eller åpne listen over pasientene dine. Du kan ha én pasientjournal åpen om gangen.",
  "s2.find.open": "Åpne pasientlisten",
  "s2.find.search": "Søk (Ctrl+Shift+P)",
  "s2.recent.title": "Nylig åpnet",
  "s2.recent.item": (fodt: string, siste: string) => `Født ${fodt} · siste konsultasjon ${siste}`,
  "s2.tabApps.title": "Apper i egne faner",
  "s2.tabApps.running": (tid: string) => `Kjører i egen fane – verten kan ikke lukke den. Tilgang til ca. ${tid}.`,
  "s2.tabApps.stale": (tid: string) => `Tilhører forrige pasient – lukk fanen. Tilgangen utløper ca. ${tid}.`,
  "s2.about.title": "Om testmiljøet",
  "s2.about.body": "nav-epj lar deg starte SMART on FHIR-apper mot en norsk test-EPJ. Alle pasienter er syntetiske. Se Systeminformasjon for innlogging, SMART-endepunkter og FHIR-ressurser.",

  "s3.title": "Pasienter",
  "s3.segment.label": "Utvalg",
  "s3.segment.mine": (n: number) => `Mine pasienter (${n})`,
  "s3.segment.recent": (n: number) => `Nylig åpnet (${n})`,
  "s3.newPatient": "Ny pasient",
  "s3.filtered": (q: string) => `Filtrert på «${q}»`,
  "s3.clearSearch": "Tøm søk",
  "s3.col.name": "Navn",
  "s3.col.born": "Fødselsdato",
  "s3.col.bornValue": (dato: string, alder: number) => `${dato} (${alder} år)`,
  "s3.col.fnr": "Fødselsnummer",
  "s3.col.fnr.sr": "Fødselsnummer skjult, slutter på",
  "s3.col.last": "Siste konsultasjon",
  "s3.col.last.ongoing": "Pågår nå",
  "s3.col.action.sr": "Handling",
  "s3.open.aria": (navn: string) => `Åpne journal for ${navn}`,
  "s3.open.tooltip": "Åpne journal",
  "s3.pager.showing": (fra: number, til: number, n: number) => `Viser ${fra}–${til} av ${n} pasienter`,
  "s3.pager.filtered": (n: number) => `(filtrert fra ${n})`,
  "s3.pager.page": (side: number, sider: number) => `Side ${side} av ${sider}`,
  "s3.pager.prev": "‹ Forrige",
  "s3.pager.prev.aria": "Forrige side",
  "s3.pager.next": "Neste ›",
  "s3.pager.next.aria": "Neste side",
  "s3.empty.search.title": (q: string) => `Ingen pasienter passer til «${q}».`,
  "s3.empty.search.body": "Sjekk stavemåten, eller søk på de siste sifrene i fødselsnummeret.",
  "s3.empty.none.title": "Du har ingen pasienter ennå.",
  "s3.empty.none.body": "Pasienter som er knyttet til deg i nav-epj vises her.",
  "s3.empty.recent": "Du har ikke åpnet noen journaler ennå.",
  "s3b.title": "Ny pasient",
  "s3b.intro": (navn: string) => `Pasienten knyttes til deg (${navn}). Bruk bare syntetiske fødselsnumre.`,
  "s3b.fornavn": "Fornavn",
  "s3b.etternavn": "Etternavn",
  "s3b.fnr": "Fødselsnummer",
  "s3b.fnr.hint": "11 siffer, for eksempel et Tenor-nummer",
  "s3b.err.fornavn": "Fornavn er påkrevd",
  "s3b.err.etternavn": "Etternavn er påkrevd",
  "s3b.err.fnr": "Fødselsnummer må bestå av 11 siffer",
  "s3b.save": "Lagre pasient",
  "s3b.saving": "Lagrer …",
  "s3b.savingStatus": "Lagrer pasient …",
  "s3b.cancel": "Avbryt",
  "s3b.saved.title": "Pasient lagret",
  "s3b.saved.body": "Pasienten er lagt til i Mine pasienter.",
  "s4.tabs.label": "Journal",
  "s4.tab.kons": "Konsultasjon",
  "s4.tab.konsDirty": "Konsultasjon •",
  "s4.tab.tidl": (n: number) => `Tidligere konsultasjoner (${n})`,
  "s4.tab.apper": (n: number) => `Apper (${n})`,
  "s4.none.title": "Ingen pågående konsultasjon",
  "s4.none.body": (navn: string) => `Start en konsultasjon for å sette diagnoser, skrive journalnotat og starte apper for ${navn}.`,
  "s4.start": "Start konsultasjon",
  "s4.ongoing.title": "Pågående konsultasjon",
  "s4.ongoing.badge": (min: number) => `◐ Pågående · ${min} min`,
  "s4.diag.label": "Diagnoser (ICPC-2 eller ICD-10)",
  "s4.diag.placeholder": "Søk på kode eller beskrivelse",
  "s4.diag.hint": "Pil ned åpner listen. Enter velger.",
  "s4.diag.show": "Vis diagnoseliste",
  "s4.diag.hide": "Skjul diagnoseliste",
  "s4.diag.noHits": "Ingen treff",
  "s4.diag.chips": "Valgte diagnoser",
  "s4.diag.none": "Ingen diagnoser valgt.",
  "s4.diag.remove": (kode: string, beskrivelse: string) => `Fjern ${kode} ${beskrivelse}`,
  "s4.diag.saved": "· lagret",
  "s4.note.label": "Journalnotat",
  "s4.save": "Lagre",
  "s4.saving": "Lagrer …",
  "s4.saving.aria": "Lagrer konsultasjon",
  "s4.finish": "Fullfør konsultasjon",
  "s4.status.dirty": "● Ulagrede endringer",
  "s4.status.saved": (tid: string) => `✔ Lagret kl. ${tid}`,
  "s4.status.error": "✖ Ikke lagret",
  "s4.saveError": "Konsultasjonen ble ikke lagret. Endringene dine er ikke borte.",
  "s4.retry": "Prøv igjen",
  "s4.saved.title": "Konsultasjon lagret",
  "s4.saved.body": (navn: string) => `Diagnoser og journalnotat er lagret for ${navn}.`,
  "s4.info.title": "Konsultasjon",
  "s4.info.started": "Startet",
  "s4.info.duration": "Varighet",
  "s4.info.doctor": "Lege",
  "s4.info.minutes": (min: number) => `${min} min`,
  "s4.empty.value": "–",
  "s4.done.note": "Konsultasjonen er fullført og skrivebeskyttet. Start en ny konsultasjon for å sette diagnoser eller starte apper.",
  "s4.done.title": "Fullført konsultasjon",
  "s4.done.ended": "Avsluttet",
  "s4.done.diag": "Diagnoser",
  "s4.done.notes": "Journalnotater",
  "s4.done.balloon.title": "Konsultasjon fullført",
  "s4.done.balloon.body": (navn: string) => `Konsultasjonen for ${navn} er skrivebeskyttet.`,
  "s4.finishDlg.title": "Fullfør konsultasjon",
  "s4.finishDlg.head": (navn: string) => `Fullføre konsultasjonen for ${navn}?`,
  "s4.finishDlg.body": "Konsultasjonen blir skrivebeskyttet. Du kan ikke endre diagnoser eller journalnotat etterpå, og apper kan ikke startes før du starter en ny konsultasjon.",
  "s4.finishDlg.unsaved": "Ulagrede endringer lagres samtidig.",
  "s4.unsavedDlg.title": "Ulagrede endringer",
  "s4.unsavedDlg.head": "Lukke journalen uten å lagre?",
  "s4.unsavedDlg.body": "Diagnoser og journalnotat du ikke har lagret, går tapt.",
  "s4.unsavedDlg.saveClose": "Lagre og lukk",
  "s4.unsavedDlg.close": "Lukk uten å lagre",
  "s4.tidl.col.date": "Dato",
  "s4.tidl.col.status": "Status",
  "s4.tidl.col.diag": "Diagnoser",
  "s4.tidl.done": "✔ Fullført",
  "s4.tidl.detail": (dato: string) => `Konsultasjon ${dato}`,
  "s4.tidl.readonly": "(skrivebeskyttet)",
  "s4.tidl.pick": "Velg en konsultasjon for å se diagnoser og journalnotater.",
  "s4.tidl.empty": "Ingen tidligere konsultasjoner.",
  "s4.apps.disabled.title": "Start en konsultasjon først.",
  "s4.apps.disabled.body": "Apper får pasient og konsultasjon fra nav-epj, og krever en pågående konsultasjon.",
  "s4.apps.start": "Start",
  "s4.apps.runningHost": "● Kjører i nav-epj",
  "s4.apps.runningTab": "● Kjører i egen fane",
  "s4.apps.help": "▣ Vindu: appen vises som en fane her i nav-epj. ↗ Ny fane: appen åpnes i en egen nettleserfane som nav-epj ikke kan lukke. ? Spør: du velger hver gang.",
  "s7.title": "Bytt pasient",
  "s7.head": (A: string, B: string) => `Bytte fra ${A} til ${B}?`,
  "s7.deeplink": (B: string) => `Du åpnet en lenke til ${B}.`,
  "s7.body.noApps": (A: string, B: string) => `Du har ${A} åpen. Journalen lukkes før du bytter til ${B}.`,
  "s7.list": "Dette skjer med det som er åpent:",
  "s7.item.journal": (A: string) => `Journal · ${A}`,
  "s7.mode.host": "▣ I nav-epj",
  "s7.effect.close": "Lukkes",
  "s7.unsaved": "Journalnotatet har ulagrede endringer. De går tapt hvis du bytter nå. Velg Avbryt for å lagre først.",
  "s7.confirm": "Lukk og bytt pasient",
  "s7.balloon.title": (B: string) => `Pasient byttet til ${B}`,
  "s7.balloon.clean": (A: string) => `Journal og apper for ${A} er lukket.`,

  "common.loading": "Laster …",
  "s3.loadError": "Feil ved lasting av pasienter",
  "s3b.err.server": "Kunne ikke opprette pasient. Kontroller opplysningene eller sjekk om pasienten finnes fra før.",
  "s4.loadError.patient": "Feil ved lasting av pasient",
  "s4.loadError.kons": "Feil ved lasting av konsultasjoner",
  "s4.tidl.ongoing": "◐ Pågående",
  "context.gender": "Kjønn",
  "context.gender.other": "Annet",
  "context.gender.unknown": "Ukjent",
  "common.close": "Lukk",
  "common.closeDialog": "Lukk dialog",
  "common.cancel": "Avbryt",
  "common.ok": "OK",
  "s8.details": "Tekniske detaljer",
  "s8.details.copy": "Kopier detaljer",
  "s9.tema.theme": "Tema",
  "s9.tema.luna": "Luna (standard)",
  "s9.tema.klassisk": "Klassisk (høy kontrast)",
  "s9.tema.reduce": "Reduser bevegelse",
  "s9.tema.text": "Tekststørrelse",
  "s9.tema.t100": "100 % (14 px)",
  "s9.tema.t125": "125 %",
  "s9.tema.t150": "150 %",
  "s5.toolbar.label": "Appverktøy",
  "s5.back": (app: string) => `Tilbake i ${app}`,
  "s5.back.tooltip": "Tilbake",
  "s5.forward": (app: string) => `Frem i ${app}`,
  "s5.forward.tooltip": "Frem",
  "s5.reload": (app: string) => `Start ${app} på nytt (ny SMART-oppstart)`,
  "s5.reload.tooltip": "Last på nytt – starter SMART-oppstarten på nytt",
  "s5.title": (app: string, navn: string, tid: string) => `${app}, ${navn}, Konsultasjon ${tid}`,
  "s5.dev": "Utviklerverktøy",
  "s5.popout": "Åpne i ny fane",
  "s5.close": "Lukk",
  "s5.iframeTitle": (app: string, clientId: string, navn: string) => `${app} (${clientId}) for ${navn}`,
  "s5.status.running": (start: string, utloper: string) => `▣ Kjører i nav-epj · startet ${start} · tilgang gyldig til ca. ${utloper}`,
  "s5.status.starting": "◐ Starter · sjekker pasientkontekst → starter app",
  "s5.status.timeout": "⚠ Svarer ikke (8 s)",
  "s5.status.error": "✖ Feil ved oppstart",
  "s5.status.session": "⚠ Innloggingen er utløpt",
  "s5.status.stale": (navn: string) => `⚠ Utdatert – tilhører ${navn}`,
  "s6.title": (app: string) => `Starter ${app} …`,
  "s6.step1": "Sjekker pasientkontekst",
  "s6.step1.ok": (navn: string, tid: string) => `OK – ${navn}, konsultasjon ${tid}`,
  "s6.step1.busy": "pågår …",
  "s6.step2": "Starter app",
  "s6.step2.wait": (origin: string) => `venter på svar fra ${origin}`,
  "s6.hint": "Svarer ikke appen innen 8 sekunder, kan du åpne den i ny fane.",
  "s6.timeout.title": "Appen svarer ikke i vinduet",
  "s6.timeout.body": (app: string) => `${app} har ikke svart på 8 sekunder. Appen kan blokkere visning inne i nav-epj.`,
  "s5.error.title": "Appen kunne ikke vises.",
  "s5.error.body": (app: string) => `${app} svarte med en feil under oppstart. Start appen på nytt, eller åpne den i ny fane.`,
  "s5.error.restart": "Start på nytt",
  "s5.session.title": "Innloggingen er utløpt. Last siden på nytt.",
  "s5.session.body": "HelseID-økten er avsluttet, så appen fikk en innloggingsside i stedet for innhold. Etter ny innlogging må du starte appen igjen.",
  "s5.session.reload": "Last på nytt",
  "s5.stale.title": (A: string, B: string) => `Appen tilhørte ${A}. Lukk eller start på nytt for ${B}.`,
  "s5.stale.body": "Aktiv pasient ble endret i en annen nettleserfane. Innholdet er skjult så du ikke jobber i feil journal.",
  "s5.stale.open": (B: string) => `Åpne journalen til ${B}`,
  "s5.popout.balloon.title": (app: string) => `${app} åpnet i ny fane`,
  "s5.popout.balloon.body": "Fanen i nav-epj er lukket. Appen fikk en ny oppstart i nettleserfanen.",
  "s5.tab.balloon.body": (navn: string) => `Ny oppstart for ${navn}. nav-epj kan ikke lukke fanen.`,
  "dev.title": (app: string) => `Utviklerverktøy – ${app}`,
  "dev.copy": "Kopier",
  "dev.close": "Lukk utviklerverktøy",
  "dev.clientId": "client_id",
  "dev.launchUrl": "Launch-URL",
  "dev.launchId": "Launch-ID",
  "dev.launchId.value": (id: string) => `${id} (brukt, engangs, 5 min)`,
  "dev.iss": "iss",
  "dev.patient": "Pasient",
  "dev.encounter": "Konsultasjon",
  "dev.started": "Startet",
  "dev.expires": "Token utløper (ca.)",
  "dev.sandbox": "sandbox",
  "dev.referrer": "referrerpolicy",
  "dev.events": "Hendelser i rammen",
  "dev.event.launch": (tid: string, status: number) => `${tid}  POST /api/launch → ${status}`,
  "dev.event.load": (tid: string, url: string) => `${tid}  iframe lastet ${url}`,
  "dev.devtoolsNote": (origin: string) => `Nettleseren lar ikke en nettside åpne utviklerverktøyene. Trykk F12 (Cmd+Alt+I på Mac), gå til Konsoll og velg rammen «${origin}» i kontekstvelgeren øverst.`,
  "dev.copied": "Utviklerinfo kopiert",
  "s6b.title": (app: string) => `Velg visning – ${app}`,
  "s6b.question": (app: string, navn: string) => `Hvordan vil du åpne ${app} for ${navn}?`,
  "s6b.legend": "Visning",
  "s6b.iframe": "▣ Vindu – inne i nav-epj. Lukkes automatisk når du bytter pasient.",
  "s6b.tab": "↗ Ny fane – egen nettleserfane. nav-epj kan ikke lukke den.",
  "s6b.remember": "Husk valget for denne appen",
  "s6b.rememberHint": "Valget lagres bare i denne nettleseren. Du kan endre det i Kontrollpanel.",
  "s6b.start": "Start",
  "s7.body.apps": (A: string, n: number, B: string) => `Du har ${A} åpen med ${n} ${n === 1 ? "app" : "apper"}. Journalen og appene i vindu lukkes før du bytter til ${B}.`,
  "s7.mode.iframe": "▣ Vindu",
  "s7.mode.tab": "↗ Ny fane",
  "s7.effect.cannot": "⚠ Kan ikke lukkes av nav-epj",
  "s7.tabWarning": (app: string, clientId: string, A: string) => `Appen i egen fane (${app}, ${clientId}) kan fortsatt vise ${A} i opptil 1 time. Lukk fanen selv.`,
  "s7.balloon.stale": (A: string) => `En app i egen fane tilhører fortsatt ${A}. Lukk fanen.`,
  "s7.staleDlg.title": (app: string) => `${app} – forrige pasient`,
  "s7.staleDlg.head": (app: string, A: string) => `${app} kjører fortsatt i en egen fane for ${A}.`,
  "s7.staleDlg.body1": (tid: string) => `nav-epj kan ikke lukke fanen eller trekke tilbake tilgangen. Tilgangen utløper ca. ${tid} (senest 1 time etter start).`,
  "s7.staleDlg.body2": (B: string) => `Gå til fanen i nettleseren og lukk den. Ikke bruk den for ${B}.`,
  "s7.staleDlg.done": "Jeg har lukket fanen",
  "s7.tabInfo.title": (app: string) => `${app} i egen fane`,
  "s7.tabInfo.head": (app: string, navn: string) => `${app} kjører i en egen fane for ${navn}.`,
  "s7.tabInfo.body": (tid: string) => `Verten kan ikke vise eller lukke fanen. Bytt til fanen i nettleseren. Tilgangen gjelder til ca. ${tid}.`,
  "s7.tabInfo.restart": "Start på nytt i ny fane",
  "s7.tabInfo.remove": "Fjern fra listen",
  "s8.title.cannotStart": (app: string) => `Kan ikke starte ${app}`,
  "s8.NO_ACTIVE_PATIENT.head": "Ingen pasient er valgt.",
  "s8.NO_ACTIVE_PATIENT.body": "Åpne en pasientjournal og start en konsultasjon før du starter appen.",
  "s8.NO_ACTIVE_PATIENT.action": "Åpne pasientliste",
  "s8.NO_ACTIVE_ENCOUNTER.head": "Pasienten har ingen pågående konsultasjon.",
  "s8.NO_ACTIVE_ENCOUNTER.body": (app: string, navn: string) => `${app} trenger en pågående konsultasjon for ${navn}. Start konsultasjonen, og start appen på nytt.`,
  "s8.NO_ACTIVE_ENCOUNTER.action": "Start konsultasjon",
  "s8.NO_ACTIVE_ENCOUNTER.balloon": (app: string) => `Start ${app} på nytt fra oppgavepanelet eller Apper-fanen.`,
  "s8.UNKNOWN_APP.head": "Appen er ikke registrert i nav-epj.",
  "s8.UNKNOWN_APP.body": (app: string) => `${app} finnes ikke i konfigurasjonen lenger. Apper registreres i application.yaml.`,
  "s8.UNKNOWN_APP.action": "Vis SMART-apper",
  "s8.FRAMING_REFUSED.title": "Appen svarer ikke",
  "s8.FRAMING_REFUSED.head": "Appen kan ikke vises i nav-epj.",
  "s8.FRAMING_REFUSED.body": (app: string) => `${app} svarte ikke innen 8 sekunder. Appen kan blokkere visning inne i nav-epj. Du kan åpne den i en ny fane i stedet.`,
  "s8.FRAMING_REFUSED.action": "Åpne i ny fane",
  "s8.SESSION_EXPIRED.title": "Innlogging utløpt",
  "s8.SESSION_EXPIRED.head": "Innloggingen er utløpt.",
  "s8.SESSION_EXPIRED.body": "Du må logge inn med HelseID på nytt. Ulagrede endringer kan gå tapt.",
  "s8.SESSION_EXPIRED.action": "Last siden på nytt",
  "s8.NETWORK.title": "Nettverksfeil",
  "s8.NETWORK.head": "Kunne ikke kontakte nav-epj.",
  "s8.NETWORK.body": "Sjekk nettverkstilkoblingen og prøv igjen.",
  "s8.NETWORK.action": "Prøv igjen",
  "s8.details.code": "Feilkode",
  "s8.details.app": "App",
  "s8.details.time": "Tid",
  "s8.details.http": "HTTP-status",
  "s8.details.call": "Kall",
  "s8.details.copied": "Detaljer kopiert",
  "common.copied.body": "Teksten ligger på utklippstavlen.",
} as const;
