export const copy = {
  "app.name": "nav-epj",
  "app.subtitle": "Test-EPJ",
  "app.test": "TEST",
  "app.testTooltip": "Testmiljø – kun syntetiske data",
  "header.search.label": "Søk etter pasient",
  "header.search.placeholder": "Søk pasient: navn eller fnr (Ctrl+Shift+P)",
  "header.search.placeholderNarrow": "Søk pasient",
  "header.user": (navn: string, autorisasjon: string, legekontor: string) => `${navn} · ${autorisasjon} · ${legekontor}`,
  "header.logout": "Logg av",
  "header.menu": "Meny",
  "nav.label": "Oppgaver",
  "pane.patient.title": "Pasient",
  "pane.patient.none": "Ingen pasient valgt.",
  "pane.patient.info": (dato: string, alder: number, kjonn: string) => `Født ${dato} (${alder} år) · ${kjonn}`,
  "pane.patient.openJournal": "Åpne journal",
  "pane.patient.find": "Finn pasient",
  "pane.patient.findOther": "Finn en annen pasient",
  "pane.apps.title": "SMART-apper",
  "pane.apps.mode.iframe": "▣ Vindu",
  "pane.apps.mode.tab": "↗ Ny fane",
  "pane.apps.mode.ask": "? Spør",
  "pane.apps.runningHost": "● Kjører i nav-epj",
  "pane.apps.runningTab": "↗ Kjører i egen fane – verten kan ikke lukke den",
  "pane.apps.stale": "Tilhører forrige pasient – lukk fanen",
  "pane.apps.disabledReason": "Start en konsultasjon først. Apper trenger en pågående konsultasjon.",
  "pane.apps.startTooltip": (app: string) => `Start ${app}`,
  "pane.system.title": "System",
  "pane.system.patients": "Pasienter",
  "pane.system.kontroll": "Kontrollpanel",
  "pane.system.sysinfo": "Systeminformasjon",
  "pane.system.logg": "Hendelseslogg",
  "pane.system.hjelp": "Hjelp",
  "pane.system.logoutNarrow": (navn: string) => `Logg av ${navn}`,
  "pane.soon.title": "Kommer",
  "pane.soon.kj": "Kjernejournal",
  "pane.soon.er": "e-resept",
  "pane.soon.em": "e-meldinger",
  "pane.soon.label": "Kommer",
  "badge.phase2": "Fase 2",
  "badge.example": "Eksempel",
  "badge.localOnly": "⚙ Kun lokalt",
  "tabs.label": "Åpne arbeidsflater",
  "tabs.start": "Start",
  "tabs.journal": (navn: string) => `Journal · ${navn}`,
  "tabs.app": (app: string, initialer: string) => `${app} · ${initialer}`,
  "tabs.app.aria": (app: string, navn: string, status: string) => `${app} for ${navn}, ${status}`,
  "tabs.close": (fane: string) => `Lukk ${fane}`,
  "tabs.closeTooltip": "Lukk (Ctrl+W)",
  "tabs.logg": "Hendelseslogg (Fase 2)",
  "status.label": "Statuslinje",
  "status.ready": "Klar",
  "status.hits": (n: number) => `${n} treff`,
  "status.patient": (navn: string) => `Aktiv pasient: ${navn}`,
  "status.patient.aria": (navn: string) => `Aktiv pasient: ${navn}. Åpne journal.`,
  "status.noPatient": "Ingen pasient valgt",
  "status.noPatient.aria": "Ingen aktiv pasient. Åpne pasientlisten.",
  "status.kons": (min: number) => `◐ Konsultasjon ${min} min`,
  "status.tabApps": (n: number) =>
    n === 1 ? `↗ ${n} app i egen fane` : `↗ ${n} apper i egen fane`,
  "status.staleApps": (n: number) => `⚠ ${n} app i fane tilhører forrige pasient`,
  "status.clock.sr": (tid: string) => `Klokken er ${tid}`,
  "balloon.close": "Lukk varsel",
  "context.label": "Pasientkontekst",
  "context.fnr": "Fødselsnummer",
  "context.fnrShow": "Vis",
  "context.fnrHide": "Skjul",
  "context.born": "Født",
  "context.age": "Alder",
  "context.ageValue": (n: number) => `${n} år`,
  "context.gender.m": "Mann",
  "context.gender.k": "Kvinne",
  "context.office": "Legekontor",
  "context.orgnr": "Org.nr.",
  "context.stale": "⚠ Utdatert",
  "live.fnrShown": "Fødselsnummer vises.",
  "live.fnrHidden": "Fødselsnummer skjult.",
  "live.journalOpened": (navn: string) => `Journal åpnet for ${navn}.`,
  "live.switched": (fra: string, til: string) => `Aktiv pasient byttet fra ${fra} til ${til}.`,
  "live.konsStarted": (navn: string) => `Konsultasjon startet for ${navn}.`,
  "live.konsDone": "Konsultasjonen er fullført.",
  "live.appRunning": (app: string) => `${app} kjører.`,
  "live.appTab": (app: string) => `${app} åpnet i ny fane.`,
  "live.back": (app: string) => `Tilbake i ${app}.`,
  "live.forward": (app: string) => `Frem i ${app}.`,
  "live.theme": (tema: string) => `Tema byttet til ${tema}.`,
  "s1.tagline": "Test-EPJ for SMART on FHIR",
  "s1.loading": "Henter brukeropplysninger …",
  "s1.loadingDetail": "Du er logget inn med HelseID. Venter på svar fra nav-epj.",
  "s1.welcome": (navn: string) => `Velkommen, ${navn}`,
  "s1.userLine": (autorisasjon: string, hpr: string) => `${autorisasjon} · HPR ${hpr}`,
  "s1.officeLine": (legekontor: string, orgnr: string) => `${legekontor} · org.nr. ${orgnr}`,
  "s1.continue": "Klikk på navnet ditt eller trykk Enter for å fortsette.",
  "s1.error.title": "Kunne ikke hente brukeropplysningene dine.",
  "s1.error.body": "Du er logget inn med HelseID, men nav-epj svarte ikke. Prøv igjen. Hvis feilen fortsetter, logg av og inn på nytt.",
  "s1.error.retry": "Prøv igjen",
  "s1.footer.test": "Testmiljø – kun syntetiske data",
  "s1.footer.login": "Innlogging skjer i HelseID før denne siden lastes.",
  "s2.greeting": (navn: string) => `God morgen, ${navn}`,
  "s2.find.title": "Finn pasient",
  "s2.find.body": "Søk i feltet øverst, eller åpne listen over pasientene dine. Du kan ha én pasientjournal åpen om gangen.",
  "s2.find.open": "Åpne pasientlisten",
  "s2.find.search": "Søk (Ctrl+Shift+P)",
  "s2.recent.title": "Nylig åpnet",
  "s2.recent.item": (fodt: string, siste: string) => `Født ${fodt} · siste konsultasjon ${siste}`,
  "s2.tabApps.title": "Apper i egne faner",
  "s2.tabApps.running": (tid: string) => `Kjører i egen fane – verten kan ikke lukke den. Tilgang til ca. ${tid}.`,
  "s2.tabApps.stale": (tid: string) => `Tilhører forrige pasient – lukk fanen. Tilgangen utløper ca. ${tid}.`,
  "s2.about.title": "Om testmiljøet",
  "s2.about.body": "nav-epj lar deg starte SMART on FHIR-apper mot en norsk test-EPJ. Alle pasienter er syntetiske. Se Systeminformasjon for innlogging, SMART-endepunkter og FHIR-ressurser.",

  "common.close": "Lukk",
  "common.closeDialog": "Lukk dialog",
  "common.cancel": "Avbryt",
  "common.ok": "OK",
  "s8.details": "Tekniske detaljer",
  "s8.details.copy": "Kopier detaljer",
  "s9.tema.theme": "Tema",
  "s9.tema.luna": "Luna (standard)",
  "s9.tema.klassisk": "Klassisk (høy kontrast)",
  "s9.tema.reduce": "Reduser bevegelse",
  "s9.tema.text": "Tekststørrelse",
  "s9.tema.t100": "100 % (14 px)",
  "s9.tema.t125": "125 %",
  "s9.tema.t150": "150 %",
} as const;
