export const copy = {
  "app.name": "nav-epj",
  "app.subtitle": "Test-EPJ",
  "app.test": "TEST",
  "app.testTooltip": "Testmiljø – kun syntetiske data",
  "header.search.label": "Søk etter pasient",
  "header.search.placeholder": "Søk pasient: navn eller fnr (Ctrl+Shift+P)",
  "header.search.placeholderNarrow": "Søk pasient",
  "header.user": (navn: string, autorisasjon: string, legekontor: string) => `${navn} · ${autorisasjon} · ${legekontor}`,
  "header.logout": "Logg av",
  "header.menu": "Meny",
  "nav.label": "Oppgaver",
  "pane.patient.title": "Pasient",
  "pane.patient.none": "Ingen pasient valgt.",
  "pane.patient.info": (dato: string, alder: number, kjonn: string) => `Født ${dato} (${alder} år) · ${kjonn}`,
  "pane.patient.openJournal": "Åpne journal",
  "pane.patient.find": "Finn pasient",
  "pane.patient.findOther": "Finn en annen pasient",
  "pane.apps.title": "SMART-apper",
  "pane.apps.mode.iframe": "▣ Vindu",
  "pane.apps.mode.tab": "↗ Ny fane",
  "pane.apps.mode.ask": "? Spør",
  "pane.apps.runningHost": "● Kjører i nav-epj",
  "pane.apps.runningTab": "↗ Kjører i egen fane – verten kan ikke lukke den",
  "pane.apps.stale": "Tilhører forrige pasient – lukk fanen",
  "pane.apps.disabledReason": "Start en konsultasjon først. Apper trenger en pågående konsultasjon.",
  "pane.apps.startTooltip": (app: string) => `Start ${app}`,
  "pane.system.title": "System",
  "pane.system.patients": "Pasienter",
  "pane.system.kontroll": "Kontrollpanel",
  "pane.system.sysinfo": "Systeminformasjon",
  "pane.system.logg": "Hendelseslogg",
  "pane.system.hjelp": "Hjelp",
  "pane.system.logoutNarrow": (navn: string) => `Logg av ${navn}`,
  "pane.soon.title": "Kommer",
  "pane.soon.kj": "Kjernejournal",
  "pane.soon.er": "e-resept",
  "pane.soon.em": "e-meldinger",
  "pane.soon.label": "Kommer",
  "badge.phase2": "Fase 2",
  "badge.example": "Eksempel",
  "badge.localOnly": "⚙ Kun lokalt",
  "tabs.label": "Åpne arbeidsflater",
  "tabs.start": "Start",
  "tabs.journal": (navn: string) => `Journal · ${navn}`,
  "tabs.app": (app: string, initialer: string) => `${app} · ${initialer}`,
  "tabs.app.aria": (app: string, navn: string, status: string) => `${app} for ${navn}, ${status}`,
  "tabs.close": (fane: string) => `Lukk ${fane}`,
  "tabs.closeTooltip": "Lukk (Ctrl+W)",
  "tabs.logg": "Hendelseslogg (Fase 2)",
  "status.label": "Statuslinje",
  "status.ready": "Klar",
  "status.hits": (n: number) => `${n} treff`,
  "status.patient": (navn: string) => `Aktiv pasient: ${navn}`,
  "status.patient.aria": (navn: string) => `Aktiv pasient: ${navn}. Åpne journal.`,
  "status.noPatient": "Ingen pasient valgt",
  "status.noPatient.aria": "Ingen aktiv pasient. Åpne pasientlisten.",
  "status.kons": (min: number) => `◐ Konsultasjon ${min} min`,
  "status.tabApps": (n: number) =>
    n === 1 ? `↗ ${n} app i egen fane` : `↗ ${n} apper i egen fane`,
  "status.staleApps": (n: number) => `⚠ ${n} app i fane tilhører forrige pasient`,
  "status.clock.sr": (tid: string) => `Klokken er ${tid}`,
  "balloon.close": "Lukk varsel",
  "context.label": "Pasientkontekst",
  "context.fnr": "Fødselsnummer",
  "context.fnrShow": "Vis",
  "context.fnrHide": "Skjul",
  "context.born": "Født",
  "context.age": "Alder",
  "context.ageValue": (n: number) => `${n} år`,
  "context.gender.m": "Mann",
  "context.gender.k": "Kvinne",
  "context.office": "Legekontor",
  "context.orgnr": "Org.nr.",
  "context.stale": "⚠ Utdatert",
  "live.fnrShown": "Fødselsnummer vises.",
  "live.fnrHidden": "Fødselsnummer skjult.",
  "live.journalOpened": (navn: string) => `Journal åpnet for ${navn}.`,
  "live.switched": (fra: string, til: string) => `Aktiv pasient byttet fra ${fra} til ${til}.`,
  "live.konsStarted": (navn: string) => `Konsultasjon startet for ${navn}.`,
  "live.konsDone": "Konsultasjonen er fullført.",
  "live.appRunning": (app: string) => `${app} kjører.`,
  "live.appTab": (app: string) => `${app} åpnet i ny fane.`,
  "live.back": (app: string) => `Tilbake i ${app}.`,
  "live.forward": (app: string) => `Frem i ${app}.`,
  "live.theme": (tema: string) => `Tema byttet til ${tema}.`,
  "s1.tagline": "Test-EPJ for SMART on FHIR",
  "s1.loading": "Henter brukeropplysninger …",
  "s1.loadingDetail": "Du er logget inn med HelseID. Venter på svar fra nav-epj.",
  "s1.welcome": (navn: string) => `Velkommen, ${navn}`,
  "s1.userLine": (autorisasjon: string, hpr: string) => `${autorisasjon} · HPR ${hpr}`,
  "s1.officeLine": (legekontor: string, orgnr: string) => `${legekontor} · org.nr. ${orgnr}`,
  "s1.continue": "Klikk på navnet ditt eller trykk Enter for å fortsette.",
  "s1.error.title": "Kunne ikke hente brukeropplysningene dine.",
  "s1.error.body": "Du er logget inn med HelseID, men nav-epj svarte ikke. Prøv igjen. Hvis feilen fortsetter, logg av og inn på nytt.",
  "s1.error.retry": "Prøv igjen",
  "s1.footer.test": "Testmiljø – kun syntetiske data",
  "s1.footer.login": "Innlogging skjer i HelseID før denne siden lastes.",
  "s2.greeting": (navn: string) => `God morgen, ${navn}`,
  "s2.find.title": "Finn pasient",
  "s2.find.body": "Søk i feltet øverst, eller åpne listen over pasientene dine. Du kan ha én pasientjournal åpen om gangen.",
  "s2.find.open": "Åpne pasientlisten",
  "s2.find.search": "Søk (Ctrl+Shift+P)",
  "s2.recent.title": "Nylig åpnet",
  "s2.recent.item": (fodt: string, siste: string) => `Født ${fodt} · siste konsultasjon ${siste}`,
  "s2.tabApps.title": "Apper i egne faner",
  "s2.tabApps.running": (tid: string) => `Kjører i egen fane – verten kan ikke lukke den. Tilgang til ca. ${tid}.`,
  "s2.tabApps.stale": (tid: string) => `Tilhører forrige pasient – lukk fanen. Tilgangen utløper ca. ${tid}.`,
  "s2.about.title": "Om testmiljøet",
  "s2.about.body": "nav-epj lar deg starte SMART on FHIR-apper mot en norsk test-EPJ. Alle pasienter er syntetiske. Se Systeminformasjon for innlogging, SMART-endepunkter og FHIR-ressurser.",

  "s3.title": "Pasienter",
  "s3.segment.label": "Utvalg",
  "s3.segment.mine": (n: number) => `Mine pasienter (${n})`,
  "s3.segment.recent": (n: number) => `Nylig åpnet (${n})`,
  "s3.newPatient": "Ny pasient",
  "s3.filtered": (q: string) => `Filtrert på «${q}»`,
  "s3.clearSearch": "Tøm søk",
  "s3.col.name": "Navn",
  "s3.col.born": "Fødselsdato",
  "s3.col.bornValue": (dato: string, alder: number) => `${dato} (${alder} år)`,
  "s3.col.fnr": "Fødselsnummer",
  "s3.col.fnr.sr": "Fødselsnummer skjult, slutter på",
  "s3.col.last": "Siste konsultasjon",
  "s3.col.last.ongoing": "Pågår nå",
  "s3.col.action.sr": "Handling",
  "s3.open.aria": (navn: string) => `Åpne journal for ${navn}`,
  "s3.open.tooltip": "Åpne journal",
  "s3.pager.showing": (fra: number, til: number, n: number) => `Viser ${fra}–${til} av ${n} pasienter`,
  "s3.pager.filtered": (n: number) => `(filtrert fra ${n})`,
  "s3.pager.page": (side: number, sider: number) => `Side ${side} av ${sider}`,
  "s3.pager.prev": "‹ Forrige",
  "s3.pager.prev.aria": "Forrige side",
  "s3.pager.next": "Neste ›",
  "s3.pager.next.aria": "Neste side",
  "s3.empty.search.title": (q: string) => `Ingen pasienter passer til «${q}».`,
  "s3.empty.search.body": "Sjekk stavemåten, eller søk på de siste sifrene i fødselsnummeret.",
  "s3.empty.none.title": "Du har ingen pasienter ennå.",
  "s3.empty.none.body": "Pasienter som er knyttet til deg i nav-epj vises her.",
  "s3.empty.recent": "Du har ikke åpnet noen journaler ennå.",
  "s3b.title": "Ny pasient",
  "s3b.intro": (navn: string) => `Pasienten knyttes til deg (${navn}). Bruk bare syntetiske fødselsnumre.`,
  "s3b.fornavn": "Fornavn",
  "s3b.etternavn": "Etternavn",
  "s3b.fnr": "Fødselsnummer",
  "s3b.fnr.hint": "11 siffer, for eksempel et Tenor-nummer",
  "s3b.err.fornavn": "Fornavn er påkrevd",
  "s3b.err.etternavn": "Etternavn er påkrevd",
  "s3b.err.fnr": "Fødselsnummer må bestå av 11 siffer",
  "s3b.save": "Lagre pasient",
  "s3b.saving": "Lagrer …",
  "s3b.savingStatus": "Lagrer pasient …",
  "s3b.cancel": "Avbryt",
  "s3b.saved.title": "Pasient lagret",
  "s3b.saved.body": "Pasienten er lagt til i Mine pasienter.",
  "s4.tabs.label": "Journal",
  "s4.tab.kons": "Konsultasjon",
  "s4.tab.konsDirty": "Konsultasjon •",
  "s4.tab.tidl": (n: number) => `Tidligere konsultasjoner (${n})`,
  "s4.tab.apper": (n: number) => `Apper (${n})`,
  "s4.none.title": "Ingen pågående konsultasjon",
  "s4.none.body": (navn: string) => `Start en konsultasjon for å sette diagnoser, skrive journalnotat og starte apper for ${navn}.`,
  "s4.start": "Start konsultasjon",
  "s4.ongoing.title": "Pågående konsultasjon",
  "s4.ongoing.badge": (min: number) => `◐ Pågående · ${min} min`,
  "s4.diag.label": "Diagnoser (ICPC-2 eller ICD-10)",
  "s4.diag.placeholder": "Søk på kode eller beskrivelse",
  "s4.diag.hint": "Pil ned åpner listen. Enter velger.",
  "s4.diag.show": "Vis diagnoseliste",
  "s4.diag.hide": "Skjul diagnoseliste",
  "s4.diag.noHits": "Ingen treff",
  "s4.diag.chips": "Valgte diagnoser",
  "s4.diag.none": "Ingen diagnoser valgt.",
  "s4.diag.remove": (kode: string, beskrivelse: string) => `Fjern ${kode} ${beskrivelse}`,
  "s4.diag.saved": "· lagret",
  "s4.note.label": "Journalnotat",
  "s4.save": "Lagre",
  "s4.saving": "Lagrer …",
  "s4.saving.aria": "Lagrer konsultasjon",
  "s4.finish": "Fullfør konsultasjon",
  "s4.status.dirty": "● Ulagrede endringer",
  "s4.status.saved": (tid: string) => `✔ Lagret kl. ${tid}`,
  "s4.status.error": "✖ Ikke lagret",
  "s4.saveError": "Konsultasjonen ble ikke lagret. Endringene dine er ikke borte.",
  "s4.retry": "Prøv igjen",
  "s4.saved.title": "Konsultasjon lagret",
  "s4.saved.body": (navn: string) => `Diagnoser og journalnotat er lagret for ${navn}.`,
  "s4.info.title": "Konsultasjon",
  "s4.info.started": "Startet",
  "s4.info.duration": "Varighet",
  "s4.info.doctor": "Lege",
  "s4.done.note": "Konsultasjonen er fullført og skrivebeskyttet. Start en ny konsultasjon for å sette diagnoser eller starte apper.",
  "s4.done.title": "Fullført konsultasjon",
  "s4.done.ended": "Avsluttet",
  "s4.done.diag": "Diagnoser",
  "s4.done.notes": "Journalnotater",
  "s4.done.balloon.title": "Konsultasjon fullført",
  "s4.done.balloon.body": (navn: string) => `Konsultasjonen for ${navn} er skrivebeskyttet.`,
  "s4.finishDlg.title": "Fullfør konsultasjon",
  "s4.finishDlg.head": (navn: string) => `Fullføre konsultasjonen for ${navn}?`,
  "s4.finishDlg.body": "Konsultasjonen blir skrivebeskyttet. Du kan ikke endre diagnoser eller journalnotat etterpå, og apper kan ikke startes før du starter en ny konsultasjon.",
  "s4.finishDlg.unsaved": "Ulagrede endringer lagres samtidig.",
  "s4.unsavedDlg.title": "Ulagrede endringer",
  "s4.unsavedDlg.head": "Lukke journalen uten å lagre?",
  "s4.unsavedDlg.body": "Diagnoser og journalnotat du ikke har lagret, går tapt.",
  "s4.unsavedDlg.saveClose": "Lagre og lukk",
  "s4.unsavedDlg.close": "Lukk uten å lagre",
  "s4.tidl.col.date": "Dato",
  "s4.tidl.col.status": "Status",
  "s4.tidl.col.diag": "Diagnoser",
  "s4.tidl.done": "✔ Fullført",
  "s4.tidl.detail": (dato: string) => `Konsultasjon ${dato}`,
  "s4.tidl.readonly": "(skrivebeskyttet)",
  "s4.tidl.pick": "Velg en konsultasjon for å se diagnoser og journalnotater.",
  "s4.tidl.empty": "Ingen tidligere konsultasjoner.",
  "s4.apps.disabled.title": "Start en konsultasjon først.",
  "s4.apps.disabled.body": "Apper får pasient og konsultasjon fra nav-epj, og krever en pågående konsultasjon.",
  "s4.apps.start": "Start",
  "s4.apps.runningHost": "● Kjører i nav-epj",
  "s4.apps.runningTab": "● Kjører i egen fane",
  "s4.apps.help": "▣ Vindu: appen vises som en fane her i nav-epj. ↗ Ny fane: appen åpnes i en egen nettleserfane som nav-epj ikke kan lukke. ? Spør: du velger hver gang.",
  "s7.title": "Bytt pasient",
  "s7.head": (A: string, B: string) => `Bytte fra ${A} til ${B}?`,
  "s7.deeplink": (B: string) => `Du åpnet en lenke til ${B}.`,
  "s7.body.noApps": (A: string, B: string) => `Du har ${A} åpen. Journalen lukkes før du bytter til ${B}.`,
  "s7.list": "Dette skjer med det som er åpent:",
  "s7.item.journal": (A: string) => `Journal · ${A}`,
  "s7.mode.host": "▣ I nav-epj",
  "s7.effect.close": "Lukkes",
  "s7.unsaved": "Journalnotatet har ulagrede endringer. De går tapt hvis du bytter nå. Velg Avbryt for å lagre først.",
  "s7.confirm": "Lukk og bytt pasient",
  "s7.balloon.title": (B: string) => `Pasient byttet til ${B}`,
  "s7.balloon.clean": (A: string) => `Journal og apper for ${A} er lukket.`,

  "common.loading": "Laster …",
  "s3.loadError": "Feil ved lasting av pasienter",
  "s3b.err.server": "Kunne ikke opprette pasient. Kontroller opplysningene eller sjekk om pasienten finnes fra før.",
  "s4.loadError.patient": "Feil ved lasting av pasient",
  "s4.loadError.kons": "Feil ved lasting av konsultasjoner",
  "s4.tidl.ongoing": "◐ Pågående",
  "context.gender": "Kjønn",
  "context.gender.other": "Annet",
  "context.gender.unknown": "Ukjent",
  "common.close": "Lukk",
  "common.closeDialog": "Lukk dialog",
  "common.cancel": "Avbryt",
  "common.ok": "OK",
  "s8.details": "Tekniske detaljer",
  "s8.details.copy": "Kopier detaljer",
  "s9.tema.theme": "Tema",
  "s9.tema.luna": "Luna (standard)",
  "s9.tema.klassisk": "Klassisk (høy kontrast)",
  "s9.tema.reduce": "Reduser bevegelse",
  "s9.tema.text": "Tekststørrelse",
  "s9.tema.t100": "100 % (14 px)",
  "s9.tema.t125": "125 %",
  "s9.tema.t150": "150 %",
} as const;
