/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsPatientIdIndexRouteImport } from './routes/patients/$patientId/index'
import { Route as PatientsPatientIdKonsultasjonKonsultasjonIdIndexRouteImport } from './routes/patients/$patientId/konsultasjon/$konsultasjonId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdIndexRoute = PatientsPatientIdIndexRouteImport.update({
  id: '/patients/$patientId/',
  path: '/patients/$patientId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdKonsultasjonKonsultasjonIdIndexRoute =
  PatientsPatientIdKonsultasjonKonsultasjonIdIndexRouteImport.update({
    id: '/patients/$patientId/konsultasjon/$konsultasjonId/',
    path: '/patients/$patientId/konsultasjon/$konsultasjonId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/konsultasjon/$konsultasjonId/': typeof PatientsPatientIdKonsultasjonKonsultasjonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patients': typeof PatientsIndexRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/konsultasjon/$konsultasjonId': typeof PatientsPatientIdKonsultasjonKonsultasjonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/konsultasjon/$konsultasjonId/': typeof PatientsPatientIdKonsultasjonKonsultasjonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patients/'
    | '/patients/$patientId/'
    | '/patients/$patientId/konsultasjon/$konsultasjonId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/patients'
    | '/patients/$patientId'
    | '/patients/$patientId/konsultasjon/$konsultasjonId'
  id:
    | '__root__'
    | '/'
    | '/patients/'
    | '/patients/$patientId/'
    | '/patients/$patientId/konsultasjon/$konsultasjonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  PatientsPatientIdIndexRoute: typeof PatientsPatientIdIndexRoute
  PatientsPatientIdKonsultasjonKonsultasjonIdIndexRoute: typeof PatientsPatientIdKonsultasjonKonsultasjonIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/': {
      id: '/patients/$patientId/'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof PatientsPatientIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/konsultasjon/$konsultasjonId/': {
      id: '/patients/$patientId/konsultasjon/$konsultasjonId/'
      path: '/patients/$patientId/konsultasjon/$konsultasjonId'
      fullPath: '/patients/$patientId/konsultasjon/$konsultasjonId/'
      preLoaderRoute: typeof PatientsPatientIdKonsultasjonKonsultasjonIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  PatientsPatientIdIndexRoute: PatientsPatientIdIndexRoute,
  PatientsPatientIdKonsultasjonKonsultasjonIdIndexRoute:
    PatientsPatientIdKonsultasjonKonsultasjonIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
