name: Build & Deploy
on: push

env:
  APP: nav-epj

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  test-and-verify:
    name: Test, lint and verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: navikt/tsm-workflows/actions/yarn@main
        with:
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: yarn lint
      - run: yarn tsc
      # - run: yarn test

  build-dev:
    name: Build for dev
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/tsm-workflows/actions/next/build@main
        id: next-build
        with:
          app: ${{ env.APP }}
          env: dev
          team: 'helseopplysninger'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      image: ${{ steps.next-build.outputs.image }}

  deploy-dev-main-warn:
    # TODO: Remove this and to re-enable deployment
    name: Deploy is disabled
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: [build-dev, test-and-verify]
    steps:
      - run: |
          echo "Deployment is disabled" >> $GITHUB_STEP_SUMMARY

  deploy-dev-main:
    name: Deploy main to dev
    # TODO: and this && false
    if: github.ref_name == 'main' && false
    environment:
      name: dev
      url: https://epj.ekstern.dev.nav.no
    runs-on: ubuntu-latest
    needs: [build-dev, test-and-verify]
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yml
          VAR: image=${{ needs.build-dev.outputs.image }}
          NAIS_DEPLOY_SUMMARY: false
