name: Build & Deploy
on:
  push:
    branches:
      - v2

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/tsm-workflows/actions/gradle/build@main
        id: build
        with:
          app: "nav-epj"
          team: helseopplysninger
          salsa: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      image: ${{ steps.build.outputs.image }}
      digest: ${{ steps.build.outputs.digest }}

  sbom:
    name: Upload SBOM for build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/tsm-workflows/actions/attest-sign@main
        with:
          image: ${{ needs.build.outputs.image }}
          digest: ${{ needs.build.outputs.digest }}
          team: helseopplysninger

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://epj.ansatt.dev.nav.no
    steps:
      - uses: actions/checkout@v6
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: "dev-gcp"
          RESOURCE: ".nais/nais.yaml"
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
